include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const
    - unnecessary_new
    - avoid_print
    - prefer_single_quotes
    - sort_pub_dependencies

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/firebase_options.dart"
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
