import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:logger/logger.dart';

import 'app.dart';
import 'core/analytics/analytics.dart';
import 'core/ads/rewarded_ads.dart';
import 'core/config/remote_config.dart';
import 'data/services/firebase_service.dart';

// NOTE: This file should be generated by FlutterFire CLI:
// Run: flutterfire configure
// For now, we'll handle the error gracefully
// import 'firebase_options.dart';

final _logger = Logger();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock orientation to portrait
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  try {
    // Initialize Firebase
    // TODO: Generate firebase_options.dart with: flutterfire configure
    // For now, using default initialization
    await Firebase.initializeApp(
      // options: DefaultFirebaseOptions.currentPlatform,
    );
    _logger.i('Firebase initialized');

    // Initialize services
    await _initializeServices();
  } catch (e, stack) {
    _logger.e('Failed to initialize app', error: e, stackTrace: stack);
    // Continue anyway to show UI with error state
  }

  runApp(
    const ProviderScope(
      child: IAmApp(),
    ),
  );
}

/// Initialize all app services
Future<void> _initializeServices() async {
  try {
    // Initialize Firebase services
    final firebaseService = FirebaseService();
    await firebaseService.initialize();

    // Sign in anonymously if not authenticated
    if (!firebaseService.isAuthenticated) {
      await firebaseService.signInAnonymously();
    }

    // Initialize Remote Config
    final remoteConfig = RemoteConfigService();
    await remoteConfig.initialize();
    _logger.i('Remote Config initialized with values: ${remoteConfig.getAllValues()}');

    // Initialize Analytics
    final analytics = AnalyticsService();
    await analytics.initialize();
    await analytics.logSessionStart();

    // Initialize Ads
    final adsService = RewardedAdsService();
    await adsService.initialize();

    _logger.i('All services initialized successfully');
  } catch (e, stack) {
    _logger.e('Failed to initialize services', error: e, stackTrace: stack);
  }
}
