/// Environment configuration
/// Replace with actual values during Firebase/AdMob setup
class Env {
  // Firebase (use firebase_options.dart generated by FlutterFire CLI)
  static const bool useFirebaseEmulator = false;
  static const String firestoreEmulatorHost = 'localhost';
  static const int firestoreEmulatorPort = 8080;

  // AdMob App IDs
  static const String androidAdMobAppId = 'ca-app-pub-3940256099942544~3347511713'; // Test ID
  static const String iosAdMobAppId = 'ca-app-pub-3940256099942544~1458002511'; // Test ID

  // AdMob Rewarded Ad Unit IDs (Test IDs - replace with real ones)
  static const String androidRewardedAdUnitId = 'ca-app-pub-3940256099942544/5224354917';
  static const String iosRewardedAdUnitId = 'ca-app-pub-3940256099942544/1712485313';

  // App Configuration
  static const String appName = 'I AM';
  static const String androidAppId = 'com.yourstudio.iam';
  static const String iosBundleId = 'com.yourstudio.iam';

  // Dynamic Links (replace with your domain)
  static const String dynamicLinksDomain = 'iam.page.link';
  static const String dynamicLinksPrefix = 'https://iam.page.link';

  // Feature Flags
  static const bool enableUGC = true;
  static const bool enableAds = true;
  static const bool enableAnalytics = true;
}
